
# Manejo de Errores o Excepciones

### ¿Qué es una excepción?

Una **excepción** es un evento que ocurre cuando se presenta un error en el programa. Por ejemplo:

- Intentar dividir entre cero.
    
- Acceder a un índice que no existe en una lista.
    
- Tratar de abrir un archivo que no existe.
    

Cuando sucede algo así, Python **lanza (raise)** una excepción. Si no la manejas, el programa se interrumpe mostrando un mensaje de error (traceback).


Tenemos una serie de clases ya definidas en Python para el manejo de excepciones, la clase padre de todas las excepciones es **BaseException**, luego una clase que hereda las características de la clase padre **Exception**, y tenemos varios tipos de clases hijas para el manejo de excepciones, como por ejemplo, que un numero no se pueda dividir entre cero, errores aritméticos, errores del sistema operativo, etc.



![](img/excepciones.png)


## Ejemplo:

En este caso haremos la prueba con una división entre cero recordar que cualquier calculadora te arrojara que no se puede dividir entre 0.

```python
try:

    10/0
    
except Exception as e:

    print(f'Ocurrio un error: {e}')
```


Ese `as e` significa:  
👉 **"Guarda el objeto de la excepción en la variable `e`"**.


- 1.Cuando ocurre un error, Python crea un **objeto de excepción** que contiene información sobre lo que pasó.  
    Ejemplo: el mensaje de error, el tipo de excepción, etc.
    
- 2.Si pones solo:
```python
except ValueError:
    print("Error de valor")
```

- Capturas el error, pero **no ves detalles** (como el mensaje específico).
    
- 3.Si usas `as e`: La variable `e` almacena ese objeto de excepción, y al imprimirlo obtienes más información.




Podemos usar **Except** para captar cualquier error pero es mejor ser especifico con el tipo de error que esperamos en este caso solo espera errores de **ValueError**

```python
try:
    numero = int("hola")
    
except ValueError as e:
    print("Detalles del error:", e)

```


## Ejemplo una excepción que no es

En este caso estamos verificando un error de división cero, no de verificar si los valores son números, así que no nos mandara la información del error ni nada, simplemente un error normal ya que esa excepción no puede manejar ese error.

```python
resultado = None
a = '10'
b = 0

try:
    resultado = a / b
except ZeroDivisionError as e:
    print(f'Ocurrio un error: {e}')

print(f'Resultado: {resultado}') # En este caso "resultado" se mantiene en None ya que entro en el error y no se asigno el valor
print('Continuamos.........')
```


