
# Tus propias excepciones

Para crear nuestra propia excepción esta tiene que heredar de "Exception"

En este caso imaginemos que esta clase de nuestra propia excepción esta en un archivo diferente:

```python

class NumerosIdenticosException(Exception):
    def __init__(self, mensaje):
#La clase padre "Exception" tiene message y le asignaremos nuestro mensaje
        self.message = mensaje


# La importamos
```

- La importamos

- Para mandar llamar una excepcion usamos raise, es necesario que este "Exception" o colocar directamente "NumerosIndenticosException" para que pueda mandar llamarla.

- raise se usa para arrojar cualquier tipo de excepción

```python
from propias_excepciones import NumerosIdenticosException

resultado = None
try:
    a = int(input('Primer número: '))
    b = int(input('Segundo número: '))
    if a == b:

        raise NumerosIdenticosException('Los números son identicos')
    resultado = a / b

except ZeroDivisionError as e:
    print(f'Error: {e}')
    
except TypeError as e:
    print(f'Error: {e}')
    
except NumerosIdenticosException as e: #<--------- Mandamos a llamar
    print(f'Error: {e}')

# else se ejecuta solo si no ocurrio ninguna excepcion
else:
    print('No se arrojo ninguna excepcion')
#Finally se va a lanzar incluso si hay una excepcion
finally:
    print('Ejecucion del bloque finally')

print(f'Resultado: {resultado}')
```